### ISSUE TITLE
Is it possible to add freelancer scraping?

### ISSUE THREAD

**Issue by serivas** [Yazan-Sharaya/upwork_analysis#1]
It'd be super useful being able to see freelancer experience, rates, etc to assess the market/competition as well as who to hire if an employer

**Comment by Yazan-Sharaya** [comment]
Unfortunately, this is not possible. Upwork doesn't show this information, even if you are logged in. And as a client, you can only see information about the freelancers who applied to a job you posted, as far as I know.
